export const customerLocales = ["en", "he", "fr", "es", "de", "pt-BR", "pt-PT"] as const;
export type CustomerLocale = typeof customerLocales[number];

export const customerDirection = (locale: CustomerLocale) => locale === "he" ? "rtl" : "ltr";
export function customerLocale(value: unknown): CustomerLocale {
  if ((customerLocales as readonly string[]).includes(String(value))) return value as CustomerLocale;
  if ((import.meta as ImportMeta & { env?: { DEV?: boolean } }).env?.DEV) console.warn("[customer-i18n] unsupported locale; using English", value);
  return "en";
}

type CustomerCopy = {
  discover: string; guide: string; cart: string; purchases: string; language: string; privateMarketplace: string;
  discoverTitle: string; adultNotice: string; guideLink: string; defaultBio: string; emptyCatalogTitle: string; emptyCatalogText: string;
  guideTitle: string; guideSteps: readonly [readonly [string, string], readonly [string, string], readonly [string, string], readonly [string, string]]; startDiscovering: string;
  creatorStorefront: string; creatorUnavailable: string; addedToCart: string; cartUpdateFailed: string; checkoutUnavailable: string; previewUnavailable: string; blurredPreview: string; addToCart: string; noContent: string; backDiscover: string;
  cartTitle: string; emptyCart: string; total: string; adultCheckout: string; secureCheckout: string; continueBrowsing: string; remove: string;
  purchasesTitle: string; noPurchases: string; delivery: string; retryDelivery: string; retryQueued: string;
  paymentChecking: string; paymentConfirmed: string; paymentProcessing: string; paymentReturn: string;
  adultsOnly: string; ageText: string; ageConfirm: string; ageError: string; privacy: string; sessionVerifying: string; sessionError: string; close: string;
  status: Record<string, string>;
};

export const customerCopy: Record<CustomerLocale, CustomerCopy> = {
  en: {
    discover: "Discover", guide: "Guide", cart: "Cart", purchases: "Purchases", language: "Language", privateMarketplace: "PRIVATE CREATOR MARKETPLACE",
    discoverTitle: "Discover creators", adultNotice: "18+ only. Preview clips are deliberately blurred. Purchased content is delivered privately in this Telegram chat after payment.", guideLink: "New here? See what you can view and access.", defaultBio: "Explore this creator’s private collection.", emptyCatalogTitle: "New creators coming soon", emptyCatalogText: "The private catalog is ready. Check back for new verified creator storefronts.",
    guideTitle: "How this marketplace works", guideSteps: [["1. Discover available creators", "Browse the published creator storefronts currently available to you."], ["2. View previews and collections", "Previews are blurred. Full paid content is never streamed in the Mini App."], ["3. Add content to your cart", "Choose collections, review the price in Cart, then continue to secure checkout."], ["4. Access purchases in Telegram", "After payment, files are delivered privately in Telegram. Purchases shows delivery status."]], startDiscovering: "Start discovering creators",
    creatorStorefront: "CREATOR STOREFRONT", creatorUnavailable: "This creator is unavailable right now.", addedToCart: "Added to cart.", cartUpdateFailed: "Could not update your cart.", checkoutUnavailable: "Secure checkout is unavailable right now. Please try again shortly.", previewUnavailable: "Preview unavailable", blurredPreview: "BLURRED PREVIEW", addToCart: "Add to cart", noContent: "No content is available from this creator yet.", backDiscover: "Back to Discover",
    cartTitle: "Your cart", emptyCart: "Your cart is empty.", total: "Total", adultCheckout: "By checking out, you confirm that you are legally an adult in your jurisdiction.", secureCheckout: "Continue to secure checkout", continueBrowsing: "Continue browsing", remove: "Remove",
    purchasesTitle: "Your purchases", noPurchases: "You have no purchases yet.", delivery: "Delivery", retryDelivery: "Retry delivery", retryQueued: "Delivery retry requested.", paymentChecking: "Checking your payment…", paymentConfirmed: "Payment confirmed. Your content is being delivered in Telegram.", paymentProcessing: "Payment is still processing.", paymentReturn: "Return to Telegram and check Purchases shortly.",
    adultsOnly: "Adults only", ageText: "This catalog contains adult content. You must be at least 18 years old and legally permitted to view it in your location.", ageConfirm: "I am 18 or older", ageError: "We could not record your age confirmation. Reopen the catalog from Telegram and try again.", privacy: "Paid content is never streamed in this Mini App. It is delivered privately by @OnlyContentMenuBot after confirmed payment.", sessionVerifying: "Verifying your Telegram session…", sessionError: "Telegram could not verify this Mini App session. Close this page and reopen the catalog from @OnlyContentMenuBot.", close: "Close",
    status: { delivered: "Delivered", queued: "Queued", partial: "Partially delivered", failed: "Delivery failed", not_ready: "Preparing delivery" },
  },
  he: {
    discover: "גילוי", guide: "מדריך", cart: "עגלה", purchases: "רכישות", language: "שפה", privateMarketplace: "שוק יוצרים פרטי",
    discoverTitle: "גלו יוצרים", adultNotice: "לגילאי 18+ בלבד. קטעי התצוגה מטושטשים במכוון. תוכן שנרכש נשלח באופן פרטי בצ׳אט Telegram זה לאחר התשלום.", guideLink: "חדשים כאן? ראו מה אפשר לצפות בו ולקבל גישה אליו.", defaultBio: "גלו את האוסף הפרטי של היוצר/ת.", emptyCatalogTitle: "יוצרים חדשים בקרוב", emptyCatalogText: "הקטלוג הפרטי מוכן. חזרו בקרוב לחנויות יוצרים מאומתות חדשות.",
    guideTitle: "כך פועל השוק", guideSteps: [["1. גלשו ביוצרים זמינים", "עיינו בחנויות היוצרים שפורסמו וזמינות לכם."], ["2. צפו בתצוגות ובאוספים", "התצוגות מטושטשות. תוכן מלא בתשלום לעולם אינו מוזרם באפליקציה."], ["3. הוסיפו תוכן לעגלה", "בחרו אוספים, בדקו את המחיר בעגלה והמשיכו לתשלום המאובטח."], ["4. קבלו רכישות ב-Telegram", "לאחר תשלום הקבצים נשלחים באופן פרטי. ברכישות מוצג סטטוס המסירה."]], startDiscovering: "התחילו לגלות יוצרים",
    creatorStorefront: "חנות יוצר/ת", creatorUnavailable: "יוצר/ת זו אינה זמינה כעת.", addedToCart: "נוסף לעגלה.", cartUpdateFailed: "לא ניתן לעדכן את העגלה.", checkoutUnavailable: "התשלום המאובטח אינו זמין כעת. נסו שוב בקרוב.", previewUnavailable: "התצוגה אינה זמינה", blurredPreview: "תצוגה מטושטשת", addToCart: "הוספה לעגלה", noContent: "אין עדיין תוכן זמין מיוצר/ת זו.", backDiscover: "חזרה לגילוי",
    cartTitle: "העגלה שלך", emptyCart: "העגלה שלך ריקה.", total: "סה״כ", adultCheckout: "בהמשך לתשלום את/ה מאשר/ת שאת/ה בגיר/ה על פי החוק באזור שלך.", secureCheckout: "המשך לתשלום מאובטח", continueBrowsing: "המשך גלישה", remove: "הסרה",
    purchasesTitle: "הרכישות שלך", noPurchases: "אין לך עדיין רכישות.", delivery: "מסירה", retryDelivery: "ניסיון מסירה חוזר", retryQueued: "התבקש ניסיון מסירה חוזר.", paymentChecking: "בודקים את התשלום…", paymentConfirmed: "התשלום אושר. התוכן שלך נשלח ב-Telegram.", paymentProcessing: "התשלום עדיין בעיבוד.", paymentReturn: "חזרו ל-Telegram ובדקו את הרכישות בקרוב.",
    adultsOnly: "למבוגרים בלבד", ageText: "קטלוג זה מכיל תוכן למבוגרים. עליך להיות בן/בת 18 לפחות ומורשה/ית לצפות בו באזור שלך.", ageConfirm: "אני בן/בת 18 ומעלה", ageError: "לא הצלחנו לשמור את אישור הגיל. פתחו מחדש את הקטלוג מ-Telegram ונסו שוב.", privacy: "תוכן בתשלום לעולם אינו מוזרם באפליקציה. הוא נשלח באופן פרטי על ידי @OnlyContentMenuBot לאחר אישור התשלום.", sessionVerifying: "מאמתים את הפעלת Telegram…", sessionError: "לא ניתן לאמת את הפעלת Telegram. סגרו את הדף ופתחו את הקטלוג מחדש מתוך @OnlyContentMenuBot.", close: "סגירה",
    status: { delivered: "נמסר", queued: "ממתין למסירה", partial: "נמסר חלקית", failed: "המסירה נכשלה", not_ready: "מכינים למסירה" },
  },
  fr: {
    discover: "Découvrir", guide: "Guide", cart: "Panier", purchases: "Achats", language: "Langue", privateMarketplace: "MARCHÉ PRIVÉ DE CRÉATEURS",
    discoverTitle: "Découvrir les créateurs", adultNotice: "Réservé aux plus de 18 ans. Les aperçus sont volontairement floutés. Le contenu acheté est livré en privé dans ce chat Telegram après paiement.", guideLink: "Nouveau ici ? Découvrez ce que vous pouvez voir et obtenir.", defaultBio: "Découvrez la collection privée de ce créateur.", emptyCatalogTitle: "De nouveaux créateurs arrivent", emptyCatalogText: "Le catalogue privé est prêt. Revenez bientôt voir les nouvelles vitrines vérifiées.",
    guideTitle: "Comment fonctionne ce marché", guideSteps: [["1. Découvrez les créateurs", "Parcourez les vitrines publiées qui vous sont disponibles."], ["2. Consultez les aperçus", "Les aperçus sont floutés. Le contenu payant complet n’est jamais diffusé dans la Mini App."], ["3. Ajoutez au panier", "Choisissez vos collections, vérifiez le prix puis passez au paiement sécurisé."], ["4. Recevez vos achats dans Telegram", "Après paiement, les fichiers sont livrés en privé. Achats indique leur statut."]], startDiscovering: "Découvrir les créateurs",
    creatorStorefront: "VITRINE DU CRÉATEUR", creatorUnavailable: "Ce créateur est indisponible pour le moment.", addedToCart: "Ajouté au panier.", cartUpdateFailed: "Impossible de mettre à jour le panier.", checkoutUnavailable: "Le paiement sécurisé est indisponible. Réessayez bientôt.", previewUnavailable: "Aperçu indisponible", blurredPreview: "APERÇU FLOUTÉ", addToCart: "Ajouter au panier", noContent: "Aucun contenu n’est encore disponible.", backDiscover: "Retour à Découvrir",
    cartTitle: "Votre panier", emptyCart: "Votre panier est vide.", total: "Total", adultCheckout: "En passant au paiement, vous confirmez être légalement majeur dans votre juridiction.", secureCheckout: "Continuer vers le paiement sécurisé", continueBrowsing: "Continuer à parcourir", remove: "Retirer",
    purchasesTitle: "Vos achats", noPurchases: "Vous n’avez pas encore d’achats.", delivery: "Livraison", retryDelivery: "Réessayer la livraison", retryQueued: "Nouvelle livraison demandée.", paymentChecking: "Vérification du paiement…", paymentConfirmed: "Paiement confirmé. Votre contenu est livré dans Telegram.", paymentProcessing: "Le paiement est toujours en cours.", paymentReturn: "Retournez dans Telegram et consultez bientôt Achats.",
    adultsOnly: "Adultes uniquement", ageText: "Ce catalogue contient du contenu pour adultes. Vous devez avoir au moins 18 ans et être autorisé à le consulter dans votre pays.", ageConfirm: "J’ai 18 ans ou plus", ageError: "Impossible d’enregistrer votre confirmation d’âge. Rouvrez le catalogue depuis Telegram.", privacy: "Le contenu payant n’est jamais diffusé dans cette Mini App. Il est livré en privé par @OnlyContentMenuBot après paiement.", sessionVerifying: "Vérification de votre session Telegram…", sessionError: "Telegram n’a pas pu vérifier cette session. Fermez cette page et rouvrez le catalogue depuis @OnlyContentMenuBot.", close: "Fermer",
    status: { delivered: "Livré", queued: "En attente", partial: "Partiellement livré", failed: "Échec de livraison", not_ready: "Préparation de la livraison" },
  },
  es: {
    discover: "Descubrir", guide: "Guía", cart: "Carrito", purchases: "Compras", language: "Idioma", privateMarketplace: "MERCADO PRIVADO DE CREADORES",
    discoverTitle: "Descubre creadores", adultNotice: "Solo mayores de 18 años. Las vistas previas se muestran borrosas intencionalmente. El contenido comprado se entrega de forma privada en este chat de Telegram tras el pago.", guideLink: "¿Eres nuevo? Mira qué puedes ver y acceder.", defaultBio: "Explora la colección privada de este creador.", emptyCatalogTitle: "Pronto habrá nuevos creadores", emptyCatalogText: "El catálogo privado está listo. Vuelve pronto para ver nuevos escaparates verificados.",
    guideTitle: "Cómo funciona este mercado", guideSteps: [["1. Descubre creadores disponibles", "Explora los escaparates publicados disponibles para ti."], ["2. Mira vistas previas y colecciones", "Las vistas previas están borrosas. El contenido de pago completo nunca se transmite en la Mini App."], ["3. Añade contenido al carrito", "Elige colecciones, revisa el precio y continúa al pago seguro."], ["4. Accede a tus compras en Telegram", "Tras el pago, los archivos se entregan en privado. Compras muestra el estado."]], startDiscovering: "Empezar a descubrir creadores",
    creatorStorefront: "ESCAPARATE DEL CREADOR", creatorUnavailable: "Este creador no está disponible ahora.", addedToCart: "Añadido al carrito.", cartUpdateFailed: "No se pudo actualizar el carrito.", checkoutUnavailable: "El pago seguro no está disponible ahora. Inténtalo de nuevo pronto.", previewUnavailable: "Vista previa no disponible", blurredPreview: "VISTA PREVIA BORROSA", addToCart: "Añadir al carrito", noContent: "Aún no hay contenido disponible de este creador.", backDiscover: "Volver a Descubrir",
    cartTitle: "Tu carrito", emptyCart: "Tu carrito está vacío.", total: "Total", adultCheckout: "Al pagar confirmas que eres legalmente adulto en tu jurisdicción.", secureCheckout: "Continuar al pago seguro", continueBrowsing: "Seguir explorando", remove: "Eliminar",
    purchasesTitle: "Tus compras", noPurchases: "Aún no tienes compras.", delivery: "Entrega", retryDelivery: "Reintentar entrega", retryQueued: "Se solicitó reintentar la entrega.", paymentChecking: "Comprobando tu pago…", paymentConfirmed: "Pago confirmado. Tu contenido se está entregando en Telegram.", paymentProcessing: "El pago sigue procesándose.", paymentReturn: "Vuelve a Telegram y revisa Compras en breve.",
    adultsOnly: "Solo adultos", ageText: "Este catálogo contiene contenido para adultos. Debes tener al menos 18 años y permiso legal para verlo en tu ubicación.", ageConfirm: "Tengo 18 años o más", ageError: "No pudimos registrar tu confirmación de edad. Vuelve a abrir el catálogo desde Telegram.", privacy: "El contenido de pago nunca se transmite en esta Mini App. @OnlyContentMenuBot lo entrega de forma privada tras el pago.", sessionVerifying: "Verificando tu sesión de Telegram…", sessionError: "Telegram no pudo verificar esta sesión. Cierra esta página y vuelve a abrir el catálogo desde @OnlyContentMenuBot.", close: "Cerrar",
    status: { delivered: "Entregado", queued: "En espera", partial: "Entregado parcialmente", failed: "Entrega fallida", not_ready: "Preparando la entrega" },
  },
  de: {
    discover: "Entdecken", guide: "Anleitung", cart: "Warenkorb", purchases: "Käufe", language: "Sprache", privateMarketplace: "PRIVATER CREATOR-MARKTPLATZ",
    discoverTitle: "Creator entdecken", adultNotice: "Nur für Personen ab 18. Vorschauen sind absichtlich unscharf. Gekaufte Inhalte werden nach der Zahlung privat in diesem Telegram-Chat geliefert.", guideLink: "Neu hier? Sieh dir an, was du ansehen und erhalten kannst.", defaultBio: "Entdecke die private Kollektion dieses Creators.", emptyCatalogTitle: "Neue Creator kommen bald", emptyCatalogText: "Der private Katalog ist bereit. Schau bald für neue verifizierte Creator-Shops wieder vorbei.",
    guideTitle: "So funktioniert dieser Marktplatz", guideSteps: [["1. Verfügbare Creator entdecken", "Durchsuche veröffentlichte Creator-Shops, die dir zur Verfügung stehen."], ["2. Vorschauen und Kollektionen ansehen", "Vorschauen sind unscharf. Vollständige bezahlte Inhalte werden nie in der Mini App gestreamt."], ["3. Inhalte in den Warenkorb legen", "Wähle Kollektionen, prüfe den Preis und gehe zur sicheren Zahlung."], ["4. Käufe in Telegram erhalten", "Nach der Zahlung werden Dateien privat geliefert. Käufe zeigt den Status."]], startDiscovering: "Creator entdecken",
    creatorStorefront: "CREATOR-SHOP", creatorUnavailable: "Dieser Creator ist derzeit nicht verfügbar.", addedToCart: "Zum Warenkorb hinzugefügt.", cartUpdateFailed: "Warenkorb konnte nicht aktualisiert werden.", checkoutUnavailable: "Die sichere Zahlung ist derzeit nicht verfügbar. Bitte versuche es bald erneut.", previewUnavailable: "Vorschau nicht verfügbar", blurredPreview: "UNSCHARFE VORSCHAU", addToCart: "Zum Warenkorb", noContent: "Für diesen Creator ist noch kein Inhalt verfügbar.", backDiscover: "Zurück zu Entdecken",
    cartTitle: "Dein Warenkorb", emptyCart: "Dein Warenkorb ist leer.", total: "Gesamt", adultCheckout: "Mit der Zahlung bestätigst du, dass du in deiner Gerichtsbarkeit volljährig bist.", secureCheckout: "Zur sicheren Zahlung", continueBrowsing: "Weiter stöbern", remove: "Entfernen",
    purchasesTitle: "Deine Käufe", noPurchases: "Du hast noch keine Käufe.", delivery: "Lieferung", retryDelivery: "Lieferung erneut versuchen", retryQueued: "Erneute Lieferung angefordert.", paymentChecking: "Zahlung wird geprüft…", paymentConfirmed: "Zahlung bestätigt. Deine Inhalte werden in Telegram geliefert.", paymentProcessing: "Die Zahlung wird noch verarbeitet.", paymentReturn: "Kehre zu Telegram zurück und prüfe bald Käufe.",
    adultsOnly: "Nur für Erwachsene", ageText: "Dieser Katalog enthält Inhalte für Erwachsene. Du musst mindestens 18 Jahre alt sein und sie an deinem Standort legal ansehen dürfen.", ageConfirm: "Ich bin 18 oder älter", ageError: "Deine Altersbestätigung konnte nicht gespeichert werden. Öffne den Katalog erneut über Telegram.", privacy: "Bezahlte Inhalte werden nie in dieser Mini App gestreamt. @OnlyContentMenuBot liefert sie nach bestätigter Zahlung privat.", sessionVerifying: "Telegram-Sitzung wird geprüft…", sessionError: "Telegram konnte diese Mini-App-Sitzung nicht prüfen. Schließe die Seite und öffne den Katalog erneut über @OnlyContentMenuBot.", close: "Schließen",
    status: { delivered: "Geliefert", queued: "Ausstehend", partial: "Teilweise geliefert", failed: "Lieferung fehlgeschlagen", not_ready: "Lieferung wird vorbereitet" },
  },
  "pt-BR": {
    discover: "Descobrir", guide: "Guia", cart: "Carrinho", purchases: "Compras", language: "Idioma", privateMarketplace: "MERCADO PRIVADO DE CRIADORES",
    discoverTitle: "Descubra criadores", adultNotice: "Apenas para maiores de 18 anos. As prévias são propositalmente borradas. O conteúdo comprado é entregue em privado neste chat do Telegram após o pagamento.", guideLink: "É novo aqui? Veja o que pode assistir e acessar.", defaultBio: "Explore a coleção privada deste criador.", emptyCatalogTitle: "Novos criadores em breve", emptyCatalogText: "O catálogo privado está pronto. Volte para ver novas vitrines verificadas.",
    guideTitle: "Como funciona este mercado", guideSteps: [["1. Descubra criadores disponíveis", "Navegue pelas vitrines publicadas disponíveis para você."], ["2. Veja prévias e coleções", "As prévias são borradas. O conteúdo pago completo nunca é transmitido na Mini App."], ["3. Adicione conteúdo ao carrinho", "Escolha coleções, confira o preço e prossiga para o pagamento seguro."], ["4. Acesse compras no Telegram", "Após o pagamento, os arquivos são entregues em privado. Compras mostra o status."]], startDiscovering: "Descobrir criadores",
    creatorStorefront: "VITRINE DO CRIADOR", creatorUnavailable: "Este criador não está disponível agora.", addedToCart: "Adicionado ao carrinho.", cartUpdateFailed: "Não foi possível atualizar o carrinho.", checkoutUnavailable: "O pagamento seguro está indisponível no momento. Tente novamente em breve.", previewUnavailable: "Prévia indisponível", blurredPreview: "PRÉVIA BORRADA", addToCart: "Adicionar ao carrinho", noContent: "Ainda não há conteúdo deste criador.", backDiscover: "Voltar a Descobrir",
    cartTitle: "Seu carrinho", emptyCart: "Seu carrinho está vazio.", total: "Total", adultCheckout: "Ao finalizar, você confirma ser legalmente adulto na sua jurisdição.", secureCheckout: "Continuar para pagamento seguro", continueBrowsing: "Continuar navegando", remove: "Remover",
    purchasesTitle: "Suas compras", noPurchases: "Você ainda não tem compras.", delivery: "Entrega", retryDelivery: "Tentar entrega novamente", retryQueued: "Nova tentativa de entrega solicitada.", paymentChecking: "Verificando pagamento…", paymentConfirmed: "Pagamento confirmado. Seu conteúdo está sendo entregue no Telegram.", paymentProcessing: "O pagamento ainda está sendo processado.", paymentReturn: "Volte ao Telegram e confira Compras em breve.",
    adultsOnly: "Somente adultos", ageText: "Este catálogo contém conteúdo adulto. Você deve ter ao menos 18 anos e permissão legal para vê-lo no seu local.", ageConfirm: "Tenho 18 anos ou mais", ageError: "Não foi possível registrar sua confirmação de idade. Reabra o catálogo pelo Telegram.", privacy: "O conteúdo pago nunca é transmitido nesta Mini App. Ele é entregue em privado por @OnlyContentMenuBot após o pagamento confirmado.", sessionVerifying: "Verificando sua sessão do Telegram…", sessionError: "O Telegram não pôde verificar esta sessão. Feche esta página e reabra o catálogo pelo @OnlyContentMenuBot.", close: "Fechar",
    status: { delivered: "Entregue", queued: "Na fila", partial: "Parcialmente entregue", failed: "Falha na entrega", not_ready: "Preparando entrega" },
  },
  "pt-PT": {
    discover: "Descobrir", guide: "Guia", cart: "Carrinho", purchases: "Compras", language: "Idioma", privateMarketplace: "MERCADO PRIVADO DE CRIADORES",
    discoverTitle: "Descubra criadores", adultNotice: "Apenas para maiores de 18 anos. As pré-visualizações são deliberadamente desfocadas. O conteúdo comprado é entregue em privado nesta conversa Telegram após o pagamento.", guideLink: "É novo aqui? Veja o que pode ver e aceder.", defaultBio: "Explore a coleção privada deste criador.", emptyCatalogTitle: "Novos criadores em breve", emptyCatalogText: "O catálogo privado está pronto. Volte para novas vitrinas verificadas.",
    guideTitle: "Como funciona este mercado", guideSteps: [["1. Descubra criadores disponíveis", "Explore as vitrinas publicadas disponíveis para si."], ["2. Veja pré-visualizações e coleções", "As pré-visualizações são desfocadas. O conteúdo pago completo nunca é transmitido na Mini App."], ["3. Adicione conteúdo ao carrinho", "Escolha coleções, reveja o preço e avance para pagamento seguro."], ["4. Aceda às compras no Telegram", "Após o pagamento, os ficheiros são entregues em privado. Compras mostra o estado."]], startDiscovering: "Descobrir criadores",
    creatorStorefront: "VITRINA DO CRIADOR", creatorUnavailable: "Este criador não está disponível agora.", addedToCart: "Adicionado ao carrinho.", cartUpdateFailed: "Não foi possível atualizar o carrinho.", checkoutUnavailable: "O pagamento seguro está indisponível neste momento. Tente novamente em breve.", previewUnavailable: "Pré-visualização indisponível", blurredPreview: "PRÉ-VISUALIZAÇÃO DESFOCADA", addToCart: "Adicionar ao carrinho", noContent: "Ainda não existe conteúdo deste criador.", backDiscover: "Voltar a Descobrir",
    cartTitle: "O seu carrinho", emptyCart: "O seu carrinho está vazio.", total: "Total", adultCheckout: "Ao pagar, confirma que é legalmente adulto na sua jurisdição.", secureCheckout: "Continuar para pagamento seguro", continueBrowsing: "Continuar a navegar", remove: "Remover",
    purchasesTitle: "As suas compras", noPurchases: "Ainda não tem compras.", delivery: "Entrega", retryDelivery: "Tentar entrega novamente", retryQueued: "Foi pedida nova tentativa de entrega.", paymentChecking: "A verificar o pagamento…", paymentConfirmed: "Pagamento confirmado. O seu conteúdo está a ser entregue no Telegram.", paymentProcessing: "O pagamento ainda está a ser processado.", paymentReturn: "Volte ao Telegram e consulte Compras em breve.",
    adultsOnly: "Apenas adultos", ageText: "Este catálogo contém conteúdo adulto. Deve ter pelo menos 18 anos e autorização legal para o ver na sua localização.", ageConfirm: "Tenho 18 anos ou mais", ageError: "Não foi possível registar a confirmação de idade. Reabra o catálogo a partir do Telegram.", privacy: "O conteúdo pago nunca é transmitido nesta Mini App. É entregue em privado pelo @OnlyContentMenuBot após pagamento confirmado.", sessionVerifying: "A verificar a sua sessão Telegram…", sessionError: "O Telegram não conseguiu verificar esta sessão. Feche esta página e reabra o catálogo a partir do @OnlyContentMenuBot.", close: "Fechar",
    status: { delivered: "Entregue", queued: "Em fila", partial: "Parcialmente entregue", failed: "Falha na entrega", not_ready: "A preparar entrega" },
  },
};
